version: "3"
services:
  jupyterlab:
    build: https://github.com/hughcameron/jupyterlab.git
    volumes:
      - "~:/home/jovyan/work"
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: "start-notebook.sh \
      --NotebookApp.password=${NOTEBOOK_PASSWORD}"
    container_name: jupyterlab
